version: '3.4'

services:
  fitnessapp:
    image: fitnessapp
    build: .
    volumes:
      - .:/app/
    environment:
      NODE_ENV: production
    expose:
      - 3000
    ports:
      - 3000:3000
    command: "npm start"